version: "3"
services:
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile
            args:
                - REACT_APP_API_URL=http://localhost:${EXPRESS_PORT}
        env_file:
            - .env
        environment:
            - PORT=${REACT_PORT}
        ports:
            - ${REACT_PORT}:${REACT_PORT}
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        env_file:
            - .env
        environment:
            - PORT=${EXPRESS_PORT}
        ports:
            - ${EXPRESS_PORT}:${EXPRESS_PORT}
    db:
        image: postgres:15.1-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
