version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile.dev
            args: 
                - REACT_APP_BACKEND_URL=http://localhost:${EXPRESS_PORT}
        env_file: 
            - .env
        environment:
            - PORT=${REACT_PORT}
        ports:
            - ${REACT_PORT}:${REACT_PORT}
        volumes:
            - ./frontend/src:/src
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile.dev
        env_file: 
            - .env
        environment:
            - PORT=${EXPRESS_PORT}
        ports:
            - ${EXPRESS_PORT}:${EXPRESS_PORT}
        volumes:
            - ./backend/src:/src
