version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile.dev
        environment:
            - PORT=3000
            - REACT_APP_BACKEND_URL=http://localhost:8080
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/src
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile.dev
        environment:
            - PORT=8080
        ports:
            - "8080:8080"
        volumes:
            - ./backend/src:/src
