version: "3"
services:
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile.dev
            args:
                - REACT_APP_BACKEND_URL=http://localhost:${EXPRESS_PORT}
        env_file:
            - .env
        environment:
            - PORT=${REACT_PORT}
        ports:
            - ${REACT_PORT}:${REACT_PORT}
        volumes:
            - ./frontend/src:/src
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        env_file:
            - .env
        environment:
            - PORT=${EXPRESS_PORT}
        ports:
            - ${EXPRESS_PORT}:${EXPRESS_PORT}
        volumes:
            - ./backend/src:/src
